workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      android:
        image: default # Codemagic's default Android image
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
