workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      android: latest
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - scribble/app/build/outputs/apk/release/*.apk
